<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit0df01a0d06af458d4ba3028d061d5119
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Symfony\\Component\\CssSelector\\' => 30,
            'Sabberworm\\CSS\\' => 15,
        ),
        'P' => 
        array (
            'Pelago\\Emogrifier\\' => 18,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Symfony\\Component\\CssSelector\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/css-selector',
        ),
        'Sabberworm\\CSS\\' => 
        array (
            0 => __DIR__ . '/..' . '/sabberworm/php-css-parser/src',
        ),
        'Pelago\\Emogrifier\\' => 
        array (
            0 => __DIR__ . '/..' . '/pelago/emogrifier/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit0df01a0d06af458d4ba3028d061d5119::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit0df01a0d06af458d4ba3028d061d5119::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit0df01a0d06af458d4ba3028d061d5119::$classMap;

        }, null, ClassLoader::class);
    }
}
